headers:
  x-user-id:
    displayName: Authentication header
    description: |
      Use this header to specify the authentication.

      **roles required:** `<<roles>>`
    type: string
    example: |
      x-user-id 54d8ae183fd30364605c8401
